### ISSUE TITLE
Fedora installation problem

### ISSUE THREAD

**Issue by rmurray2** [Yelp/MOE#439]
Best I can tell part of the problem is that
    `cmake_path`
is equal to 
    `None`
after 
    `find_path`
runs

The full error I get is:

Traceback (most recent call last):
  File "setup.py", line 238, in <module>
    'install': InstallCppComponents,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 202, in run
    env=env,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'rfind'

And this is what `cmake_full_command` looks like right before it is passed to the `subprocess.Popen` which is described as `#Run cmake`:
`[None, '-DMOE_PYTHON_INCLUDE_DIR=/usr/include/python2.7', '-DMOE_PYTHON_LIBRARY=/usr/lib/libpython2.7.so.1.0', '/home/rm/MOE/moe/optimal_learning/cpp']`

On Fedora 22

**Comment by rmurray2** [comment]
My mistake - I neglected to install one of the dependencies: `cmake`
